asernts

diff --git a/scripts/bin/hht b/scripts/bin/hht
--- a/scripts/bin/hht
+++ b/scripts/bin/hht
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+remoteIPv4="192.168.179.23"
+remoteIPv6="60:CF:84:BE:BC:36"
+homeLapUser="moritzgleissner"
+
 # check for flags
 printOutput=false
 while getopts "h""p" opt; do
@@ -85,6 +89,7 @@ collectedData=$(threadedSsh 2>/dev/null)
 export dataArray=$(echo -e "$collectedData" | sort -t';' -k1 -n | grep -v 'sshProcess')
 # add custom number option
 dataArray+="\ncustom number|custom number"
+dataArray+="\nhome lap|home lap"
 
 preview() {
   info=$(echo -e "$dataArray" | grep "^$1" | cut -d'|' -f2)
@@ -95,6 +100,9 @@ preview() {
   # if custom number is selected
   elif [[ $info == *"custom number"* ]]; then
     echo -e "Enter a custom number"
+    return
+  elif [[ $info == *"home lap"* ]]; then
+    echo -e "Use the home lap"
     return
   fi
   IFS=';' read -r -a infoArray <<<"$info"
@@ -127,6 +135,33 @@ if [ "$connection" == "custom number" ]; then
     echo "$command"
   else
     # suppress output
+    eval "$command"
+  fi
+  exit 0
+elif [ "$connection" == "home lap" ]; then
+  # if printOutput is set and true
+  command="ssh -X -Y -o StrictHostKeyChecking=no -L 3300:localhost:3300 $homeLapUser@$remoteIPv4 2>/dev/null"
+  if [ "$printOutput" == "true" ]; then
+    echo "$command"
+  else
+    # check if ipv6 is not available available then use "systemctl stop wg-quick-GOutpost.service" to use vpn
+    if ! ping -c 1 -W 1 $remoteIPv6 >/dev/null 2>&1; then
+      systemctl start wg-quick-GOutpost.service 2>/dev/null
+      if [ $? -ne 0 ]; then
+        echo "Failed to start wg-quick-GOutpost.service"
+        exit 1
+      fi
+      # try to connect if not use wake up over lan
+      if ! ping -c 1 -W 1 $remoteIPv6 >/dev/null 2>&1; then
+        # wake up over lan
+        wakeonlan $remoteIPv6 >/dev/null 2>&1
+        # check with loop on show loading wheel
+        while ! ping -c 1 -W 1 $remoteIPv6 >/dev/null 2>&1; do
+          sleep 1
+        done
+      fi
+    fi
+
     eval "$command"
   fi
   exit 0
