615 current  2024-08-01 21:11:29  24.11.20240723.dc14ed9  6.9.9-asahi                          *

diff --git a/scripts/bin/hhtf b/scripts/bin/hhtf
--- a/scripts/bin/hhtf
+++ b/scripts/bin/hhtf
@@ -5,55 +5,55 @@ axiiWorkspace="flux"
 
 # check for flags
 while getopts "h""w" opt; do
-	case $opt in
-	h)
-		echo "Usage: hhtf"
-		echo "Starts a tmux session with a ssh connection to a remote machine."
-		echo "This script is intended to be used with hht."
-		exit 0
-		;;
-	w) # set workspace
-		axiiChooseWorkspace=true
-		;;
-	\?)
-		echo "Invalid option: -$OPTARG" >&2
-		exit 1
-		;;
-	esac
+  case $opt in
+  h)
+    echo "Usage: hhtf"
+    echo "Starts a tmux session with a ssh connection to a remote machine."
+    echo "This script is intended to be used with hht."
+    exit 0
+    ;;
+  w) # set workspace
+    axiiChooseWorkspace=true
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  esac
 done
 
 # look for hht binary with which
 if [[ $(which hht >/dev/null) ]]; then
-	echo "hht binary not found"
-	exit 1
+  echo "hht binary not found"
+  exit 1
 fi
 
 sshCommand=$(hht -p)
 
 if [[ $sshCommand == "" ]]; then
-	echo "No ssh command found"
-	exit 1
+  echo "No ssh command found"
+  exit 1
 fi
 
 if [[ $axiiChooseWorkspace ]]; then
-	axiiPossibleWorkspaces=$(eval "$sshCommand 'bash -ci \"axii w list\" | grep \"-\" | cut -c 5- | cut -f1 -d\":\"'")
-	axiiWorkspace=$(echo -e "${axiiPossibleWorkspaces[@]}" | fzf --ansi --prompt=" workspaces  " --height=~50 --layout=reverse --border --exit-0)
+  axiiPossibleWorkspaces=$(eval "$sshCommand 'bash -ci \"axii w list\" | grep \"-\" | cut -c 5- | cut -f1 -d\":\"'")
+  axiiWorkspace=$(echo -e "${axiiPossibleWorkspaces[@]}" | fzf --ansi --prompt=" workspaces  " --height=~50 --layout=reverse --border --exit-0)
 fi
 
 if [[ $axiiWorkspace == "" ]]; then
-	echo "No workspace selected"
-	exit 1
+  echo "No workspace selected"
+  exit 1
 fi
 
 session="hhtf"
 
 # if session exists, attach to it else create it
 if tmux has-session -t $session 2>/dev/null; then
-	echo "Session $session already exists. Attaching to it."
-	tmux attach -t $session
-	exit 0
+  echo "Session $session already exists. Attaching to it."
+  tmux attach -t $session
+  exit 0
 else
-	tmux new-session -d -s $session
+  tmux new-session -d -s $session
 fi
 
 # init all windows
